### ISSUE TITLE
notify接口无效

### ISSUE THREAD

**Issue by KingMario** [leancloud/cloud-code-alipay#3]
日志显示

    notify params: {}

不论是使用req.params或是req.body均无效。

**Comment by westlinkin** [comment]
我也碰到这个问题了，看[这个链接](https://forum.leancloud.cn/t/leancloud/247/9?u=westlinkin)可以解决

**Comment by KingMario** [comment]
这个问题的答案是我写的，哈哈

**Comment by KingMario** [comment]
这个链接的答案是我写的，哈哈。
somebody 把 那个绕坑的代码加进去然后关闭这个issue吧。

**Comment by KingMario** [comment]
这个链接的答案是我写的，哈哈。
已发pull request。
issue closing
